-- 1.
-- select * from customers where account_balance>1500;
-- 2.
-- select * from transactions order by transaction_date DESC;
-- 3.
-- select distinct transaction_mode from transactions;
-- 4.
-- select * from transactions order by amount desc limit 5;
-- 5.
-- select * from customers where name like 'A%';
-- 6.
-- select customer_id,SUM(amount) AS total_amount
-- FROM transactions
-- GROUP BY customer_id;
-- 7.
-- select customer_id,SUM(amount) AS total_amount from transactions group by customer_id having SUM(amount)>2000;
-- 8.
-- select c.name,t.amount,t.transaction_type from customers c join transactions t ON c.customer_id = t.customer_id;
-- 9.
-- select customer_id,name,account_balance,DENSE_RANK() over(order by account_balance desc) as rank_no  from customers;
-- 10.
-- select customer_id,AVG(amount) as avg_transaction from transactions group by customer_id having AVG(amount)>(select AVG(amount) from transactions);
